aws_region          = "eu-west-1"
profile_name        = "irland"
owner               = "bwieckow"
environment_type    = "dev"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.0.0/24"
private_subnet_cidr = "10.0.1.0/24"
