name: Auto Assign to Project DevOps

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move to Backlog
        uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: DevOps
          column: Backlog
          repo-token: ${{ secrets.READ_PROJECTS_GITHUB_TOKEN }}