name: Move new issues into Todo

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.1.0
        with:
          project: DevOps
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}