name: Slack Project Notifier

on:
  project_card:
      types: [created, moved, converted, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Magical Slack Notifier
        uses: hayuna/github-action-slack-project-notifier@1.2.1
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.DEVOPS_SLACK_WEBHOOK }}
          PROJECT: ${{ secrets.PROJECT }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
