# This is a workflow to see what will be affected with upcoming changes

name: Terraform PLAN

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "plan"
  plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Set AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    # Runs a `terraform plan` command for project-* using the runners shell
    - name: Run terraform PLAN for project-iam
      run: |
        cd ./project-iam
        terraform init
        terraform plan -var-file=frankfurt.tfvars

    # Should be commented out on first deployment
    - name: Run terraform PLAN for project-core
      run: |
        cd ./project-core
        terraform init
        terraform plan -var-file=frankfurt.tfvars

    # Should be commented out on first and second deployment
    - name: Run terraform PLAN for project-apps-dev
      run: |
        cd ./project-apps-dev
        terraform init
        terraform plan -var-file=frankfurt.tfvars
